version: "3.9"

services:
  api:
    container_name: api_container
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - ${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}
    depends_on:
      - db
    networks:
      - default_network


  nginx:
      build: nginx
      container_name: nginx_container
      restart: on-failure
      ports:
          - ${NGIN:-80}:${NGINX_PORT:-80}
      depends_on:
          - api

  db:
      container_name: db_container
      image: postgres:14-alpine
      environment:
        - POSTGRES_DB=${POSTGRES_DB:-ecommerce}
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      volumes:
        - pgdata_development:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
